[tool.poetry]
name = "valleys"
version = "0.1.0"
description = ""
authors = ["Arthur Koehl <avkoehl@ucdavis.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pynhd = "^0.15.1"
pygeohydro = "^0.15.1"
pandas = "^2.1.0"
numpy = "^1.25.2"
matplotlib = "^3.7.2"
seaborn = "^0.12.2"
geopandas = "^0.13.2"

[tool.poetry.group.dev.dependencies]
ipython = "^8.15.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
